In [1]:
import os
import numpy as np
from tqdm.notebook import tqdm
from skimage.io import imread
from skimage.transform import resize
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import load_img, img_to_array



In [2]:
# Define the CNN model
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(36, activation='softmax'))  # Adjusted output layer to match number of classes

In [3]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 32)      896       


                                                                 
 max_pooling2d (MaxPooling2  (None, 63, 63, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 61, 61, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 30, 30, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 28, 28, 128)       73856     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 14, 14, 128)       0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 25088)             0         
          

In [5]:
data_dir = r'C:\Users\shilp\OneDrive\Documents\Luminar\Internship\BSL\Data'
categories = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

X = []
Y = []

for category in tqdm(categories):
    folder_path = os.path.join(data_dir, category)
    for img_name in os.listdir(folder_path):
        img_path = os.path.join(folder_path, img_name)
        img = load_img(img_path, target_size=(128, 128))  # Load and resize image
        img = img_to_array(img) / 255.0  # Convert image to array and normalize
        X.append(img)
        Y.append(categories.index(category))

X = np.array(X)
Y = np.array(Y)

  0%|          | 0/24 [00:00<?, ?it/s]

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_train

array([[[[0.98039216, 0.        , 1.        ],
         [1.        , 0.00392157, 1.        ],
         [1.        , 0.        , 1.        ],
         ...,
         [0.69411767, 0.7058824 , 0.6784314 ],
         [0.7137255 , 0.72156864, 0.7019608 ],
         [0.70980394, 0.7176471 , 0.69803923]],

        [[1.        , 0.        , 0.9882353 ],
         [0.87058824, 0.6901961 , 0.87058824],
         [0.8352941 , 0.7137255 , 0.8352941 ],
         ...,
         [0.69803923, 0.70980394, 0.68235296],
         [0.7019608 , 0.70980394, 0.6901961 ],
         [0.7019608 , 0.7137255 , 0.6862745 ]],

        [[1.        , 0.        , 1.        ],
         [0.8039216 , 0.73333335, 0.78039217],
         [0.7647059 , 0.76862746, 0.7490196 ],
         ...,
         [0.69411767, 0.7058824 , 0.6784314 ],
         [0.7019608 , 0.7137255 , 0.6862745 ],
         [0.7058824 , 0.7176471 , 0.6901961 ]],

        ...,

        [[1.        , 0.        , 0.99607843],
         [0.44705883, 0.27058825, 0.24705882]

In [7]:
X_test

array([[[[1.        , 0.        , 0.99607843],
         [1.        , 0.        , 1.        ],
         [0.99607843, 0.00392157, 0.9882353 ],
         ...,
         [0.6431373 , 0.64705884, 0.6156863 ],
         [0.6431373 , 0.64705884, 0.6156863 ],
         [0.6431373 , 0.64705884, 0.6156863 ]],

        [[0.92941177, 0.04705882, 0.9254902 ],
         [0.7137255 , 0.59607846, 0.69803923],
         [0.69411767, 0.59607846, 0.67058825],
         ...,
         [0.6392157 , 0.6431373 , 0.6117647 ],
         [0.6392157 , 0.6431373 , 0.6117647 ],
         [0.6313726 , 0.63529414, 0.6039216 ]],

        [[0.92941177, 0.05098039, 0.9137255 ],
         [0.6313726 , 0.6392157 , 0.5882353 ],
         [0.63529414, 0.64705884, 0.5803922 ],
         ...,
         [0.6392157 , 0.6431373 , 0.61960787],
         [0.6392157 , 0.6431373 , 0.61960787],
         [0.63529414, 0.6392157 , 0.6156863 ]],

        ...,

        [[0.4862745 , 0.43529412, 0.36078432],
         [0.49019608, 0.4392157 , 0.3647059 ]

In [8]:
Y_train

array([23, 12, 22, ..., 13,  2, 18])

In [9]:
Y_test

array([22,  1,  2, ...,  6,  5,  3])

In [10]:
#X_train=np.array(X_train)
#X_test=np.array(X_test)
#Y_train=np.array(Y_train)
#Y_test=np.array(Y_test)

In [11]:
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True
)

In [12]:
history = model.fit(datagen.flow(X_train, Y_train, batch_size=32), epochs=10, validation_data=(X_test, Y_test))

Epoch 1/10
242/242 [==============================] - 459s 2s/step - loss: 2.4084 - accuracy: 0.2726 - val_loss: 1.0447 - val_accuracy: 0.6134
Epoch 2/10
242/242 [==============================] - 423s 2s/step - loss: 0.9748 - accuracy: 0.6740 - val_loss: 0.8739 - val_accuracy: 0.7230
Epoch 3/10
242/242 [==============================] - 412s 2s/step - loss: 0.5221 - accuracy: 0.8249 - val_loss: 0.4605 - val_accuracy: 0.8718
Epoch 4/10
242/242 [==============================] - 410s 2s/step - loss: 0.3616 - accuracy: 0.8778 - val_loss: 0.1670 - val_accuracy: 0.9380
Epoch 5/10
242/242 [==============================] - 420s 2s/step - loss: 0.2598 - accuracy: 0.9139 - val_loss: 0.2980 - val_accuracy: 0.9034
Epoch 6/10
242/242 [==============================] - 420s 2s/step - loss: 0.2476 - accuracy: 0.9150 - val_loss: 0.1874 - val_accuracy: 0.9276
Epoch 7/10
242/242 [==============================] - 414s 2s/step - loss: 0.1899 - accuracy: 0.9372 - val_loss: 0.1098 - val_accuracy: 0.9643

In [13]:
test_loss, test_accuracy = model.evaluate(X_test, Y_test)



61/61 [==============================] - 28s 446ms/step - loss: 0.0352 - accuracy: 0.9891


In [14]:
model.save('keras_model.h5')


C:\Users\shilp\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [15]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

def predict_sign_language_class(image_path, model_path='keras_model.h5'):
    # Load the saved model
    model = load_model(model_path)

    # Load and preprocess the image
    img = image.load_img(image_path, target_size=(128, 128))
    img_array = image.img_to_array(img) / 255.0  # Convert image to array and normalize
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    # Make predictions
    predictions = model.predict(img_array)

    # Get the predicted class
    predicted_class_index = np.argmax(predictions)
    predicted_class = chr(65 + predicted_class_index)  # Convert index to character

    return predicted_class


In [16]:
image_path = r'C:\Users\shilp\OneDrive\Desktop\Sign language\Data\A\Image_1698499705.962042.jpg'
predicted_class = predict_sign_language_class(image_path)
print("Predicted class:", predicted_class)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\shilp\\OneDrive\\Desktop\\Sign language\\Data\\A\\Image_1698499705.962042.jpg'

In [ ]:
image_path = r"C:\Users\shilp\OneDrive\Desktop\Sign language\Data\B\Image_1698501383.3889585.jpg"
predicted_class = predict_sign_language_class(image_path)
print("Predicted class:", predicted_class)

1/1 [==============================] - 0s 84ms/step
Predicted class: B
